#services:
#  app:
#    container_name: Spring-Boot-Application
#    image: 'docker-spring-boot-postgres:latest'
#    build:
#      context: .
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
##    environment:
##      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
##      - SPRING_DATASOURCE_USERNAME=postgres
##      - SPRING_DATASOURCE_PASSWORD=12345678
##      - SPRING_HIBERNATE_DDL_AUTO=update
#    networks:
#      - spring-boot-network
#  db:
#    image: postgres
#    container_name: postgres
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=12345678
#    networks:
#      - spring-boot-network
#networks:
#  spring-boot-network:
#    driver: bridge
