application:
  security:
    jwt:
      secret-key : e243ff66df6ab45aa9e0c22da3507e5d89820ed30b6260d3e445e6137eda43c1
      expiration : 86400000
      refresh-token :
        expiration : 604800000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123@Pakistan
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true